### ISSUE TITLE
how to test a single image?

### ISSUE THREAD

**Issue by SJTUzhanglj** [rbgirshick/py-faster-rcnn#246]
How to test my own images with object proposal regions unknown, using the pretrained model?

**Comment by GBJim** [comment]
Hi @SJTUzhanglj 
Please refer to https://github.com/rbgirshick/py-faster-rcnn/blob/master/tools/demo.py
The demo script demonstrates how to detect objects in a single image.
The core is the `im_detect` function imported from lib/fast_rcnn/test.py

**Comment by SJTUzhanglj** [comment]
And the objective proposal boxes need not be extracted before testing? @GBJim

**Comment by GBJim** [comment]
Hi @SJTUzhanglj 

The answer is no. Faster R-CNN no longer needs pre-computed object proposals(ex: selective search) for detection. That's why Faster R-CNN is Faster :dash: 
The network structure of Faster R-CNN contains Region Proposal Networks(RPN) which generates proposals.
You can refer to [Figure2](https://raw.githubusercontent.com/sunshineatnoon/Paper-Collection/master/images/faster-rcnn.png) from the paper

**Comment by SJTUzhanglj** [comment]
Thank you for your reminder, i understand it @GBJim
