### ISSUE TITLE
Pascal VOC training failure without Imagenet models

### ISSUE THREAD

**Issue by mbuckler** [rbgirshick/py-faster-rcnn#273]
I've cloned the repo and followed the main readme instructions, but have encountered something odd. My goal is to train and test on Pascal VOC 2007 as shown in the readme, but when I execute:

./experiments/scripts/faster_rcnn_alt_opt.sh 0 VGG_CNN_M_1024 pascal_voc --set EXP_DIR foobar RNG_SEED 42

I experience the following error, and then the console hangs

Loading pretrained model weights from data/imagenet_models/VGG_CNN_M_1024.v2.caffemodel
F0725 15:54:36.400033  1801 io.cpp:54] Check failed: fd != -1 (-1 vs. -1) File not found: data/imagenet_models/VGG_CNN_M_1024.v2.caffemodel
*** Check failure stack trace: ***

Granted, these models don't exist since I skipped downloading them, but it would seem odd that a pretrained model is needed for training. Are these weights simply used as an initializer?

**Comment by mbuckler** [comment]
I should note that after downloading the imagenet model training does run, however I am still interested in why the imagenet model is needed for training a fresh network, thanks

**Comment by GBJim** [comment]
Hi @mbuckler 
Please refer to [issue #238](https://github.com/rbgirshick/py-faster-rcnn/issues/238) for training without pre-trainined models

Most of the training of object detection tasks requires a pre-trained model, usually trained from ImageNet.
It's a typical approach of CNN-based algorithms in Computer Vision. 
The reason is that we can leverage the learned features and "Fine-Tune" the net to adapt new domain.

It's possible to train Faster R-CNN without pre-trained models, but usually, we don't have enough data to converge the neural net.

**Comment by mbuckler** [comment]
Hi GBJim, thank you for the explanation
