### ISSUE TITLE
web demo with py-faster-rcnn

### ISSUE THREAD

**Issue by PierreHao** [rbgirshick/py-faster-rcnn#30]
py-faster-rcnn runs well in terminal, but when i do a web demo with webpy, it doesn't work, the problem occurs in net.forward(**forward_kwargs). Sometimes forward runs slow with gpu mode, the time costs as cpu mode, sometimes it core dump. And for the first image , it runs well, but after first image, it will run slow as cpu mode randomly. Does anyone can solve this problem?
With fast-rcnn, webpy runs well.
 @rbgirshick

**Comment by twtygqyy** [comment]
Hi @PierreHao I tried to implement a web demo using django. I found that fast-rcnn works well with pre-loaded net, while for py-faster-rcnn, it takes more than 30s for each image if I load the model in advance. However, it is fine if I read the model every time for detection.
I thought it is caused by caffe sine when I update the caffe version for fast-rcnn and py-faster-rcnn, I meet the same situation.
How did you solve the problem you mentioned? I'm wondering if my problem is similar to yours

**Comment by vikasranga** [comment]
Hi @PierreHao/ @twtygqyy,
can you provide source code of web demo you have implemented?

**Comment by home3k** [comment]
how did you solve this problem ? bro.  @PierreHao

**Comment by PierreHao** [comment]
Sorry, I reply so late. That is called by the switch between gpu mode and cpu mode. When you start web demo, there is a thread independent which will call cpu mode automatic, so you should set_mode_gpu() before do forward every time. @home3k, @vikasranga , @twtygqyy 
I hope this will help you!

**Comment by rnsandeep** [comment]
Thanks very much. @PierreHao set_mode_gpu()  this solved.
