### ISSUE TITLE
how to change the batchsize when training the rpn model?

### ISSUE THREAD

**Issue by zimenglan-sysu-512** [rbgirshick/py-faster-rcnn#51]
how to change the batch size when training the rpn model, since i have a large dataset, and the code so far, the batch size is 1.  And by the way, if change the batch size of rpn training, the performace will increase?
Thanks

**Comment by chrert** [comment]
Currently, it's not possible to increase the image batch size when training the RPN (see assertions in the code).

@rbgirshick Is there any particular reason for that or is it simply not implemented? At a first glance, I would say it could be done with a few changes in anchor_target_layer.py, proposal_layer.py and proposal_target_layer.py.

**Comment by rbgirshick** [comment]
It's just not implemented. A reasonable workaround, which is already used, is to set `iter_size: N` in the solver, in which N is the batch size you want (currently 2 for end to end training). This may be slightly less efficient than batching, but since the inputs are spatially large operating on one image at a time isn't too bad (plus if you use more than one image there's some wasted computation where padding is introduced to fill the 4D tensor).
