### ISSUE TITLE
How to understand this codebase?

### ISSUE THREAD

**Issue by anandsaha** [rbgirshick/py-faster-rcnn#721]
What would be a good way to understand how Faster RCNN is implemented here? Is it just 'deep dive into it', or are there any documentation available on how the code is laid out? Is there any minimalistic implementation of FRCNN anywhere? (I searched but could not find).

**Comment by PentaHiggs** [comment]
Do you have a solid understanding of how it is supposed to work and are trying to figure out this specific implementation or are you trying to get a grasp on Faster RCNN in general?  If it's the latter case, I found it helpful to check out the predecessors to Faster RCNN, namely RCNN (https://arxiv.org/abs/1311.2524) , Fast R-CNN(https://arxiv.org/abs/1311.2524), and https://arxiv.org/pdf/1406.4729.pdf.  Especially Fast R-CNN, since this codebase is intended to be an improved version of it, so there's a lot of code reuse from that project (which is also on github).  The paper for Faster R-CNN omits a lot of details that you'll be able to find in those three other papers that proceed it.  As for documentation, I sadly have not been able to find any good documentation, even in other reimplementations of this on github.  To get started, well, I think identifying what every caffe layer used in the demo corresponds to in the paper is a good idea.  Looking through the Fast R-CNN paper might also be a good idea

**Comment by anandsaha** [comment]
@PentaHiggs Thanks for your pointers! 

"or are you trying to get a grasp on Faster RCNN in general?" This is more like it to begin with.

"The paper for Faster R-CNN omits a lot of details that you'll be able to find in those three other papers that proceed it." That's an excellent advice. I never tried to look at the code from the perspective from the earlier two papers. Thanks!
